# Generated by Django 3.2.9 on 2021-11-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(max_length=100),
        ),
    ]
